-- Tabel penugasan kelas binaan Guru BK
-- Digunakan untuk memfilter dropdown "Pilih Kelas / Rombel Siswa"
-- agar hanya menampilkan kelas binaan milik Guru BK yang login.

CREATE TABLE IF NOT EXISTS public.bk_assignments (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL,
    kelas character varying(255) NOT NULL,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone,
    CONSTRAINT fk_bk_assignments_user_id
        FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_bk_assignments_user_kelas
    ON public.bk_assignments (user_id, kelas);

GRANT ALL ON TABLE public.bk_assignments TO anon;
GRANT ALL ON TABLE public.bk_assignments TO authenticated;
GRANT ALL ON TABLE public.bk_assignments TO service_role;

-- Seed awal: penugasan kelas binaan untuk Guru BK (user_id 4 = Lestari Indra Sumantri)
INSERT INTO public.bk_assignments (user_id, kelas)
SELECT 4, k.kelas
FROM (SELECT 'IX A' AS kelas UNION SELECT 'IX B' UNION SELECT 'IX C') k
ON CONFLICT DO NOTHING;
